"""Named MMGP-style presets for Forge's optional memory controls."""


MEMORY_SETTING_KEYS = (
    "forge_memory_management_enabled",
    "forge_memory_budgets_enabled",
    "forge_memory_pinned_memory_enabled",
    "forge_memory_async_transfers_enabled",
    "forge_memory_residency_hints_enabled",
    "forge_memory_working_vram_mb",
    "forge_memory_unet_budget_mb",
    "forge_memory_text_encoder_budget_mb",
    "forge_memory_vae_budget_mb",
    "forge_memory_controlnet_budget_mb",
    "forge_memory_pinned_memory_percent",
    "forge_memory_async_streams",
    "forge_memory_keep_unet_loaded",
    "forge_memory_keep_text_encoder_loaded",
    "forge_memory_keep_vae_loaded",
    "forge_memory_keep_controlnet_loaded",
)

MEMORY_PROFILE_CHOICES = (
    "Custom",
    "HighRAM_HighVRAM",
    "HighRAM_LowVRAM",
    "LowRAM_HighVRAM",
    "LowRAM_LowVRAM",
    "VerylowRAM_LowVRAM",
)

# These are Forge-compatible translations of MMGP's five hardware profiles.
MEMORY_PROFILES = {
    "HighRAM_HighVRAM": {
        "forge_memory_management_enabled": True,
        "forge_memory_budgets_enabled": False,
        "forge_memory_pinned_memory_enabled": True,
        "forge_memory_async_transfers_enabled": True,
        "forge_memory_residency_hints_enabled": True,
        "forge_memory_working_vram_mb": 0,
        "forge_memory_unet_budget_mb": 0,
        "forge_memory_text_encoder_budget_mb": 0,
        "forge_memory_vae_budget_mb": 0,
        "forge_memory_controlnet_budget_mb": 0,
        "forge_memory_pinned_memory_percent": 45,
        "forge_memory_async_streams": 2,
        "forge_memory_keep_unet_loaded": True,
        "forge_memory_keep_text_encoder_loaded": True,
        "forge_memory_keep_vae_loaded": True,
        "forge_memory_keep_controlnet_loaded": True,
    },
    "HighRAM_LowVRAM": {
        "forge_memory_management_enabled": True,
        "forge_memory_budgets_enabled": True,
        "forge_memory_pinned_memory_enabled": True,
        "forge_memory_async_transfers_enabled": True,
        "forge_memory_residency_hints_enabled": True,
        "forge_memory_working_vram_mb": 1024,
        "forge_memory_unet_budget_mb": 6144,
        "forge_memory_text_encoder_budget_mb": 4096,
        "forge_memory_vae_budget_mb": 2048,
        "forge_memory_controlnet_budget_mb": 2048,
        "forge_memory_pinned_memory_percent": 45,
        "forge_memory_async_streams": 2,
        "forge_memory_keep_unet_loaded": False,
        "forge_memory_keep_text_encoder_loaded": True,
        "forge_memory_keep_vae_loaded": True,
        "forge_memory_keep_controlnet_loaded": True,
    },
    "LowRAM_HighVRAM": {
        "forge_memory_management_enabled": True,
        "forge_memory_budgets_enabled": False,
        "forge_memory_pinned_memory_enabled": False,
        "forge_memory_async_transfers_enabled": False,
        "forge_memory_residency_hints_enabled": True,
        "forge_memory_working_vram_mb": 0,
        "forge_memory_unet_budget_mb": 0,
        "forge_memory_text_encoder_budget_mb": 0,
        "forge_memory_vae_budget_mb": 0,
        "forge_memory_controlnet_budget_mb": 0,
        "forge_memory_pinned_memory_percent": 45,
        "forge_memory_async_streams": 2,
        "forge_memory_keep_unet_loaded": True,
        "forge_memory_keep_text_encoder_loaded": True,
        "forge_memory_keep_vae_loaded": True,
        "forge_memory_keep_controlnet_loaded": True,
    },
    "LowRAM_LowVRAM": {
        "forge_memory_management_enabled": True,
        "forge_memory_budgets_enabled": True,
        "forge_memory_pinned_memory_enabled": False,
        "forge_memory_async_transfers_enabled": False,
        "forge_memory_residency_hints_enabled": False,
        "forge_memory_working_vram_mb": 2048,
        "forge_memory_unet_budget_mb": 4096,
        "forge_memory_text_encoder_budget_mb": 2048,
        "forge_memory_vae_budget_mb": 1024,
        "forge_memory_controlnet_budget_mb": 2048,
        "forge_memory_pinned_memory_percent": 45,
        "forge_memory_async_streams": 2,
        "forge_memory_keep_unet_loaded": False,
        "forge_memory_keep_text_encoder_loaded": False,
        "forge_memory_keep_vae_loaded": False,
        "forge_memory_keep_controlnet_loaded": False,
    },
    "VerylowRAM_LowVRAM": {
        "forge_memory_management_enabled": True,
        "forge_memory_budgets_enabled": True,
        "forge_memory_pinned_memory_enabled": False,
        "forge_memory_async_transfers_enabled": False,
        "forge_memory_residency_hints_enabled": False,
        "forge_memory_working_vram_mb": 3072,
        "forge_memory_unet_budget_mb": 3072,
        "forge_memory_text_encoder_budget_mb": 1024,
        "forge_memory_vae_budget_mb": 512,
        "forge_memory_controlnet_budget_mb": 1024,
        "forge_memory_pinned_memory_percent": 30,
        "forge_memory_async_streams": 1,
        "forge_memory_keep_unet_loaded": False,
        "forge_memory_keep_text_encoder_loaded": False,
        "forge_memory_keep_vae_loaded": False,
        "forge_memory_keep_controlnet_loaded": False,
    },
}


def get_memory_profile(name):
    """Return a copy so UI edits cannot mutate the shared preset."""

    values = MEMORY_PROFILES.get(name)
    return dict(values) if values is not None else None
